# Generated by Django 4.2.11 on 2026-03-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectapprovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapprovalrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='projects.project'),
        ),
    ]
