# Generated by Django 4.2.11 on 2026-03-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectapprovalrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapprovalrequest',
            name='last_seen_approvals',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
