# Generated by Django 4.2.11 on 2026-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_person2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
