# Generated by Django 4.2.11 on 2026-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resourceprofile_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceprofile',
            name='resource_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
