# Generated by Django 4.2.11 on 2026-04-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_timelineapprovalrequest'),
        ('resources', '0003_alter_resourceprofile_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeentries', to='timelines.timeline'),
        ),
    ]
