# Generated by Django 4.2.11 on 2026-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='hours_allocated',
            field=models.PositiveIntegerField(default=0, help_text='Estimated hours allocated to this phase'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='hours_consumed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='timeline',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
